### ISSUE TITLE
RealTerm issue

### ISSUE THREAD

**Issue by BijayNanda** [BijayNanda/Technical-issue-#1]
I am using Realterm to get information from SB device but after change the laptop now it is not working. 
Connection and settings are below...

- Baud- 115200
- Using TTL converter

![Realterm issue pic 2](https://user-images.githubusercontent.com/108881027/191704701-9b80e245-b4fc-4619-9261-ed601f07862b.jpeg)

- Connection is like (SB device)RX to TX (TTL Converter) ,  similarly TX to RX and GND to GND.

After sending any command it is showing **Chars sent aren't displayed when half-duplex is set**

**Comment by vjkajla** [comment]
Here are my seetings 

<img width="514" alt="realterm1" src="https://user-images.githubusercontent.com/13237031/191726261-04ffcbff-d540-4acf-86ba-e9d40c803a01.png">
<img width="513" alt="realterm3" src="https://user-images.githubusercontent.com/13237031/191726267-830312d8-1d39-4263-88e3-f39ac01bdba4.png">

**Comment by BijayNanda** [comment]
Issue was with connecting cable (which do connect TTL converter to the laptop). After replacing this cable the issue has solved.  Thanks @vjkajla
